# Generated by Django 4.2.26 on 2025-11-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ASN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=18, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('tempat_lahir', models.CharField(max_length=50)),
                ('tanggal_lahir', models.DateField()),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('agama', models.CharField(choices=[('ISLAM', 'Islam'), ('KRISTEN', 'Kristen'), ('KATOLIK', 'Katolik'), ('HINDU', 'Hindu'), ('BUDDHA', 'Buddha'), ('KONGHUCU', 'Konghucu')], max_length=10)),
                ('alamat', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('telepon', models.CharField(max_length=15)),
                ('jabatan', models.CharField(max_length=100)),
                ('pangkat', models.CharField(max_length=50)),
                ('golongan', models.CharField(max_length=5)),
                ('unit_kerja', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='asn_fotos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
