# Generated by Django 4.2.26 on 2025-11-29 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuratPerintahTugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dasar_surat', models.TextField(verbose_name='Dasar Surat')),
                ('nomor_spt', models.CharField(max_length=50, verbose_name='Nomor SPT')),
                ('tempat_pelaksanaan', models.CharField(max_length=100, verbose_name='Tempat Pelaksanaan')),
                ('waktu_pelaksanaan', models.DateTimeField(verbose_name='Waktu Pelaksanaan')),
                ('tanggal_pelaksanaan', models.DateField(verbose_name='Tanggal Pelaksanaan')),
                ('nama_kegiatan', models.CharField(max_length=200, verbose_name='Nama Kegiatan')),
                ('tempat_ditetapkan', models.CharField(max_length=100, verbose_name='Tempat Ditetapkan')),
                ('tanggal_ditetapkan', models.DateField(verbose_name='Tanggal Ditetapkan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('penandatangan', models.ManyToManyField(related_name='spt_penandatangan', to='asn_app.asn', verbose_name='Penandatangan')),
                ('peserta', models.ManyToManyField(related_name='spt_peserta', to='asn_app.asn', verbose_name='Peserta')),
            ],
        ),
    ]
