# Generated by Django 4.2.26 on 2025-11-29 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0002_suratperintahtugas'),
    ]

    operations = [
        migrations.CreateModel(
            name='KopSurat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Kop Surat')),
                ('gambar', models.ImageField(upload_to='kop_surat/', verbose_name='Gambar Kop Surat')),
                ('deskripsi', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='suratperintahtugas',
            name='kop_surat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asn_app.kopsurat', verbose_name='Kop Surat'),
        ),
    ]
