# Generated by Django 4.2.26 on 2025-11-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0003_kopsurat_suratperintahtugas_kop_surat'),
    ]

    operations = [
        migrations.AddField(
            model_name='suratperintahtugas',
            name='tanggal_akhir_pelaksanaan',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Akhir Pelaksanaan'),
        ),
    ]
