# Generated by Django 4.2.26 on 2025-12-03 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0004_suratperintahtugas_tanggal_akhir_pelaksanaan'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuratSantunanKorpri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_surat', models.CharField(max_length=100, verbose_name='Nomor Surat')),
                ('tanggal_surat', models.DateField(verbose_name='Tanggal Surat')),
                ('tempat_ditetapkan', models.CharField(max_length=100, verbose_name='Tempat Ditetapkan')),
                ('instansi_tujuan_surat', models.CharField(max_length=200, verbose_name='Instansi Tujuan Surat')),
                ('kota_tujuan_surat', models.CharField(max_length=100, verbose_name='Kota Tujuan Surat')),
                ('sifat', models.CharField(max_length=100, verbose_name='Sifat')),
                ('lampiran', models.CharField(max_length=100, verbose_name='Lampiran')),
                ('perihal', models.CharField(max_length=200, verbose_name='Perihal')),
                ('tujuan', models.CharField(max_length=200, verbose_name='Tujuan')),
                ('isi_surat_pertama', models.TextField(verbose_name='Isi Surat Pertama')),
                ('isi_surat_kedua', models.TextField(verbose_name='Isi Surat Kedua')),
                ('penutup_surat', models.TextField(verbose_name='Penutup Surat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kop_surat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asn_app.kopsurat', verbose_name='Kop Surat')),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surat_santunan', to='asn_app.asn', verbose_name='Pegawai')),
                ('penandatangan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penandatangan_santunan', to='asn_app.asn', verbose_name='Penandatangan')),
            ],
        ),
    ]
