# Generated by Django 4.2.26 on 2025-12-03 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0005_suratsantunankorpri'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suratsantunankorpri',
            name='isi_surat_kedua',
        ),
        migrations.RemoveField(
            model_name='suratsantunankorpri',
            name='isi_surat_pertama',
        ),
        migrations.RemoveField(
            model_name='suratsantunankorpri',
            name='penutup_surat',
        ),
        migrations.RemoveField(
            model_name='suratsantunankorpri',
            name='tujuan',
        ),
    ]
