# Generated by Django 4.2.26 on 2025-12-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0006_remove_suratsantunankorpri_isi_surat_kedua_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asn',
            name='nama_istri_suami',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama Istri/Suami'),
        ),
    ]
