# Generated by Django 4.2.26 on 2025-12-03 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0007_asn_nama_istri_suami'),
    ]

    operations = [
        migrations.AddField(
            model_name='suratperintahtugas',
            name='kuasa_pengguna_anggaran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spt_kuasa_pengguna_anggaran', to='asn_app.asn', verbose_name='Kuasa Pengguna Anggaran'),
        ),
    ]
