# Generated by Django 4.2.26 on 2025-12-03 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0008_suratperintahtugas_kuasa_pengguna_anggaran'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suratperintahtugas',
            name='penandatangan',
        ),
        migrations.AddField(
            model_name='suratperintahtugas',
            name='penandatangan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spt_penandatangan', to='asn_app.asn', verbose_name='Penandatangan'),
        ),
    ]
