# Generated by Django 4.2.26 on 2025-12-04 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0009_remove_suratperintahtugas_penandatangan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaDinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kepada', models.CharField(max_length=255)),
                ('dari', models.CharField(max_length=255)),
                ('tanggal', models.DateField()),
                ('nomor', models.CharField(max_length=255)),
                ('sifat', models.CharField(max_length=255)),
                ('lampiran', models.CharField(max_length=255)),
                ('hal', models.CharField(max_length=255)),
                ('isi_surat', models.TextField()),
                ('penutup_surat', models.TextField()),
                ('kop_surat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asn_app.kopsurat')),
                ('pegawai', models.ManyToManyField(blank=True, to='asn_app.asn')),
                ('penanda_tangan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penanda_tangan_nota_dinas', to='asn_app.asn')),
            ],
        ),
    ]
