# Generated by Django 4.2.26 on 2025-12-05 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0010_notadinas'),
    ]

    operations = [
        migrations.CreateModel(
            name='HariLibur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(unique=True, verbose_name='Tanggal Libur')),
                ('nama_hari', models.CharField(max_length=100, verbose_name='Nama Hari Libur')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Hari Libur',
                'ordering': ['tanggal'],
            },
        ),
    ]
