# Generated by Django 4.2.26 on 2025-12-05 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0011_harilibur'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuratCuti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempat_ditetapkan', models.CharField(max_length=100, verbose_name='Tempat Ditetapkan')),
                ('tanggal_surat', models.DateField(verbose_name='Tanggal Surat')),
                ('tujuan_surat', models.CharField(max_length=200, verbose_name='Tujuan Surat')),
                ('tanggal_awal', models.DateField(verbose_name='Tanggal Awal Cuti')),
                ('tanggal_akhir', models.DateField(verbose_name='Tanggal Akhir Cuti')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kop_surat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asn_app.kopsurat', verbose_name='Kop Surat')),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surat_cuti_pegawai', to='asn_app.asn', verbose_name='Pegawai')),
                ('penandatangan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surat_cuti_penandatangan', to='asn_app.asn', verbose_name='Penandatangan')),
            ],
            options={
                'verbose_name_plural': 'Surat Cuti',
                'ordering': ['-tanggal_surat'],
            },
        ),
    ]
