# Generated by Django 4.2.26 on 2025-12-05 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0012_suratcuti'),
    ]

    operations = [
        migrations.CreateModel(
            name='SisaCuti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sisa_tahun_n', models.IntegerField(default=0, verbose_name='Sisa Tahun N')),
                ('sisa_tahun_n_1', models.IntegerField(default=0, verbose_name='Sisa Tahun N-1')),
                ('sisa_tahun_n_2', models.IntegerField(default=0, verbose_name='Sisa Tahun N-2')),
                ('total_sisa_cuti', models.IntegerField(default=0, verbose_name='Total Sisa Cuti')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pegawai', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sisa_cuti', to='asn_app.asn', verbose_name='Pegawai')),
            ],
            options={
                'verbose_name_plural': 'Sisa Cuti',
                'ordering': ['pegawai__nama'],
            },
        ),
    ]
