# Generated by Django 4.2.26 on 2025-12-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0013_sisacuti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sisacuti',
            name='sisa_tahun_n',
            field=models.IntegerField(default=12, verbose_name='Sisa Tahun N'),
        ),
    ]
