# Generated by Django 4.2.26 on 2025-12-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0014_alter_sisacuti_sisa_tahun_n'),
    ]

    operations = [
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nis', models.CharField(max_length=20, unique=True)),
                ('kelas', models.CharField(max_length=20)),
                ('jurusan', models.CharField(max_length=50)),
                ('alamat', models.TextField()),
                ('no_hp', models.CharField(blank=True, max_length=15)),
            ],
        ),
    ]
