# Generated by Django 4.2.26 on 2025-12-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0015_siswa'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswa',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='siswa_fotos/'),
        ),
    ]
