# Generated by Django 4.2.26 on 2025-12-07 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0016_siswa_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswa',
            name='nama_orang_tua',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nama Orang Tua'),
        ),
    ]
