# Generated by Django 4.2.26 on 2025-12-07 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0017_siswa_nama_orang_tua'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuratKeterangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_surat', models.CharField(max_length=100, verbose_name='Nomor Surat')),
                ('tempat_ditetapkan', models.CharField(max_length=100, verbose_name='Tempat Ditetapkan')),
                ('tanggal_ditetapkan', models.DateField(verbose_name='Tanggal Ditetapkan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pegawai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pegawai_sk', to='asn_app.asn', verbose_name='Pegawai (ASN)')),
                ('penandatangan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penandatangan_sk', to='asn_app.asn', verbose_name='Penandatangan')),
                ('siswa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asn_app.siswa', verbose_name='Siswa')),
            ],
        ),
    ]
