# Generated by Django 4.2.26 on 2025-12-07 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0018_suratketerangan'),
    ]

    operations = [
        migrations.AddField(
            model_name='suratketerangan',
            name='isi_surat',
            field=models.TextField(blank=True, verbose_name='Isi Surat'),
        ),
    ]
