# Generated by Django 4.2.26 on 2025-12-07 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0019_suratketerangan_isi_surat'),
    ]

    operations = [
        migrations.AddField(
            model_name='suratketerangan',
            name='kop_surat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asn_app.kopsurat', verbose_name='Kop Surat'),
        ),
    ]
