# Generated by Django 4.2.26 on 2025-12-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0020_suratketerangan_kop_surat'),
    ]

    operations = [
        migrations.AddField(
            model_name='suratcuti',
            name='lampiran_surat',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lampiran Surat'),
        ),
        migrations.AddField(
            model_name='suratcuti',
            name='nomor_surat',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nomor Surat'),
        ),
        migrations.AddField(
            model_name='suratcuti',
            name='perihal_surat',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Perihal Surat'),
        ),
        migrations.AddField(
            model_name='suratcuti',
            name='sifat_surat',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sifat Surat'),
        ),
    ]
