# Generated by Django 4.2.26 on 2025-12-07 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0021_suratcuti_lampiran_surat_suratcuti_nomor_surat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuratResmi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempat_ditetapkan', models.CharField(max_length=100, verbose_name='Tempat Ditetapkan')),
                ('tanggal_ditetapkan', models.DateField(verbose_name='Tanggal Ditetapkan')),
                ('pejabat_tujuan_surat', models.CharField(max_length=200, verbose_name='Pejabat Tujuan Surat')),
                ('kota_tujuan_surat', models.CharField(max_length=100, verbose_name='Kota Tujuan Surat')),
                ('nomor', models.CharField(max_length=50, verbose_name='Nomor Surat')),
                ('sifat', models.CharField(max_length=100, verbose_name='Sifat Surat')),
                ('lampiran', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lampiran')),
                ('perihal', models.CharField(max_length=200, verbose_name='Perihal')),
                ('pembuka_surat', models.TextField(verbose_name='Pembuka Surat')),
                ('isi_surat', models.TextField(verbose_name='Isi Surat')),
                ('penutup_surat', models.TextField(verbose_name='Penutup Surat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kop_surat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asn_app.kopsurat', verbose_name='Kop Surat')),
                ('pegawai', models.ManyToManyField(blank=True, related_name='surat_resmi_pegawai', to='asn_app.asn', verbose_name='Pegawai Terkait')),
                ('penandatangan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surat_resmi_penandatangan', to='asn_app.asn', verbose_name='Penandatangan')),
            ],
            options={
                'verbose_name_plural': 'Surat Resmi',
                'ordering': ['-tanggal_ditetapkan'],
            },
        ),
    ]
