# Generated by Django 4.2.26 on 2025-12-07 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0022_suratresmi'),
    ]

    operations = [
        migrations.AddField(
            model_name='suratresmi',
            name='tanggal_kegiatan',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Kegiatan'),
        ),
        migrations.AddField(
            model_name='suratresmi',
            name='tempat_kegiatan',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tempat Kegiatan'),
        ),
        migrations.AddField(
            model_name='suratresmi',
            name='waktu_kegiatan',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Waktu Kegiatan'),
        ),
    ]
