# Generated by Django 4.2.26 on 2025-12-08 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0023_suratresmi_tanggal_kegiatan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suratketerangan',
            name='penandatangan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penandatangan_sk', to='asn_app.asn', verbose_name='Penandatangan'),
        ),
    ]
