# Generated by Django 6.0 on 2025-12-09 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0024_alter_suratketerangan_penandatangan'),
    ]

    operations = [
        migrations.CreateModel(
            name='SPTJM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_surat', models.CharField(max_length=100, verbose_name='Nomor Surat')),
                ('isi_surat', models.TextField(verbose_name='Isi Surat')),
                ('penutup_surat', models.TextField(verbose_name='Penutup Surat')),
                ('tempat_ditetapkan', models.CharField(max_length=100, verbose_name='Tempat Ditetapkan')),
                ('tanggal_ditetapkan', models.DateField(verbose_name='Tanggal Ditetapkan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pegawai', models.ManyToManyField(related_name='sptjm_pegawai', to='asn_app.asn', verbose_name='Pegawai')),
                ('penandatangan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sptjm_penandatangan', to='asn_app.asn', verbose_name='Penandatangan')),
            ],
        ),
    ]
