# Generated by Django 6.0 on 2025-12-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0026_sptjm_kop_surat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='nama',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
