# Generated by Django 6.0 on 2025-12-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0027_alter_siswa_nama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='jurusan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
