# Generated by Django 6.0 on 2025-12-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0028_alter_siswa_jurusan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='alamat',
            field=models.TextField(blank=True, null=True),
        ),
    ]
