# Generated by Django 6.0 on 2025-12-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0029_alter_siswa_alamat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='no_hp',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
