# Generated by Django 6.0 on 2025-12-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0030_alter_siswa_no_hp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='nama_orang_tua',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama Orang Tua'),
        ),
    ]
