# Generated by Django 6.0 on 2025-12-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0031_alter_siswa_nama_orang_tua'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='nis',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
