# Generated by Django 6.0 on 2025-12-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0032_alter_siswa_nis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='nis',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
