# Generated by Django 6.0 on 2025-12-10 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0033_alter_siswa_nis'),
    ]

    operations = [
        migrations.CreateModel(
            name='SPMT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_surat', models.CharField(max_length=100, verbose_name='Nomor Surat')),
                ('tempat_ditetapkan', models.CharField(max_length=100, verbose_name='Tempat Ditetapkan')),
                ('tanggal_surat', models.DateField(verbose_name='Tanggal Surat')),
                ('peraturan', models.CharField(max_length=255, verbose_name='Peraturan')),
                ('nomor_peraturan', models.CharField(max_length=100, verbose_name='Nomor Peraturan')),
                ('tahun_peraturan', models.CharField(max_length=4, verbose_name='Tahun Peraturan')),
                ('tentang', models.TextField(verbose_name='Tentang')),
                ('tanggal_terhitung', models.DateField(verbose_name='Tanggal Terhitung Mulai')),
                ('sebagai', models.CharField(max_length=255, verbose_name='Sebagai')),
                ('tempat_tugas', models.CharField(max_length=255, verbose_name='Tempat Tugas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pegawai', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spmt_pegawai', to='asn_app.asn', verbose_name='Pegawai')),
                ('penandatangan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spmt_penandatangan', to='asn_app.asn', verbose_name='Penandatangan')),
            ],
        ),
    ]
