# Generated by Django 6.0 on 2025-12-10 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0034_spmt'),
    ]

    operations = [
        migrations.AddField(
            model_name='spmt',
            name='kop_surat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asn_app.kopsurat', verbose_name='Kop Surat'),
        ),
    ]
