# Generated by Django 6.0 on 2025-12-11 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0035_spmt_kop_surat'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoKegiatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='foto_kegiatan/')),
                ('keterangan', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('spt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto_kegiatan', to='asn_app.suratperintahtugas')),
            ],
        ),
    ]
