# Generated by Django 4.2.27 on 2025-12-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0036_fotokegiatan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asn',
            name='nip',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True),
        ),
    ]
