# Generated by Django 4.2.27 on 2025-12-15 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0037_alter_asn_nip'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuratUmum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pembuka_surat', models.TextField(verbose_name='Pembuka Surat')),
                ('isi_surat', models.TextField(verbose_name='Isi Surat')),
                ('penutup_surat', models.TextField(verbose_name='Penutup Surat')),
                ('tempat_ditetapkan', models.CharField(max_length=100, verbose_name='Tempat Ditetapkan')),
                ('tanggal_ditetapkan', models.DateField(verbose_name='Tanggal Ditetapkan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surat_umum_pegawai', to='asn_app.asn', verbose_name='Pegawai')),
                ('penandatangan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surat_umum_penandatangan', to='asn_app.asn', verbose_name='Penandatangan')),
            ],
        ),
    ]
