# Generated by Django 4.2.27 on 2025-12-15 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0038_suratumum'),
    ]

    operations = [
        migrations.AddField(
            model_name='suratumum',
            name='kop_surat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asn_app.kopsurat', verbose_name='Kop Surat'),
        ),
    ]
