# Generated by Django 4.2.26 on 2025-12-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0039_suratumum_kop_surat'),
    ]

    operations = [
        migrations.AddField(
            model_name='suratperintahtugas',
            name='hasil_yang_dicapai',
            field=models.TextField(blank=True, null=True, verbose_name='Hasil yang Dicapai'),
        ),
        migrations.AddField(
            model_name='suratperintahtugas',
            name='kesimpulan_dan_saran',
            field=models.TextField(blank=True, null=True, verbose_name='Kesimpulan dan Saran'),
        ),
        migrations.AddField(
            model_name='suratperintahtugas',
            name='latar_belakang',
            field=models.TextField(blank=True, null=True, verbose_name='Latar Belakang'),
        ),
        migrations.AddField(
            model_name='suratperintahtugas',
            name='maksud_dan_tujuan',
            field=models.TextField(blank=True, null=True, verbose_name='Maksud dan Tujuan'),
        ),
        migrations.AddField(
            model_name='suratperintahtugas',
            name='penutup',
            field=models.TextField(blank=True, null=True, verbose_name='Penutup'),
        ),
    ]
