# Generated by Django 4.2.26 on 2025-12-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0040_suratperintahtugas_hasil_yang_dicapai_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suratperintahtugas',
            name='sifat_surat',
            field=models.CharField(choices=[('Biasa', 'Biasa'), ('Penting', 'Penting'), ('Rahasia', 'Rahasia')], default='Biasa', max_length=10, verbose_name='Sifat Surat'),
        ),
        migrations.AddField(
            model_name='suratperintahtugas',
            name='tanggal_dibuat_laporan',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Dibuat Laporan'),
        ),
    ]
