# Generated by Django 6.0.1 on 2026-01-12 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0041_suratperintahtugas_sifat_surat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suratcuti',
            name='alasan_cuti',
            field=models.TextField(blank=True, null=True, verbose_name='Alasan Cuti'),
        ),
    ]
