# Generated by Django 4.2.27 on 2026-03-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0042_suratcuti_alasan_cuti'),
    ]

    operations = [
        migrations.AddField(
            model_name='sisacuti',
            name='initial_tahun_n',
            field=models.IntegerField(default=12, verbose_name='Alokasi Awal Tahun N'),
        ),
        migrations.AddField(
            model_name='sisacuti',
            name='initial_tahun_n_1',
            field=models.IntegerField(default=6, verbose_name='Alokasi Awal Tahun N-1'),
        ),
        migrations.AddField(
            model_name='sisacuti',
            name='initial_tahun_n_2',
            field=models.IntegerField(default=6, verbose_name='Alokasi Awal Tahun N-2'),
        ),
        migrations.AlterField(
            model_name='sisacuti',
            name='sisa_tahun_n_1',
            field=models.IntegerField(default=6, verbose_name='Sisa Tahun N-1'),
        ),
        migrations.AlterField(
            model_name='sisacuti',
            name='sisa_tahun_n_2',
            field=models.IntegerField(default=6, verbose_name='Sisa Tahun N-2'),
        ),
        migrations.AlterField(
            model_name='sisacuti',
            name='total_sisa_cuti',
            field=models.IntegerField(default=24, verbose_name='Total Sisa Cuti'),
        ),
    ]
