# Generated by Django 4.2.27 on 2026-03-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0043_sisacuti_initial_tahun_n_sisacuti_initial_tahun_n_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suratcuti',
            name='jenis_cuti',
            field=models.CharField(blank=True, choices=[('Cuti Tahunan', 'Cuti Tahunan'), ('Cuti Sakit', 'Cuti Sakit'), ('Cuti Alasan Penting', 'Cuti Alasan Penting'), ('Cuti Diluar Tanggungan Negara', 'Cuti Diluar Tanggungan Negara'), ('Cuti Melahirkan', 'Cuti Melahirkan'), ('Cuti Besar', 'Cuti Besar')], max_length=50, null=True, verbose_name='Jenis Cuti'),
        ),
    ]
