# Generated by Django 4.2.27 on 2026-03-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0044_suratcuti_jenis_cuti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suratcuti',
            name='jenis_cuti',
            field=models.CharField(choices=[('Cuti Tahunan', 'Cuti Tahunan'), ('Cuti Sakit', 'Cuti Sakit'), ('Cuti Alasan Penting', 'Cuti Alasan Penting'), ('Cuti Diluar Tanggungan Negara', 'Cuti Diluar Tanggungan Negara'), ('Cuti Melahirkan', 'Cuti Melahirkan'), ('Cuti Besar', 'Cuti Besar')], default='Cuti Tahunan', max_length=50, verbose_name='Jenis Cuti'),
        ),
    ]
