# Generated by Django 4.2.27 on 2026-03-31 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0045_alter_suratcuti_jenis_cuti'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuratPanggilanSiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_surat', models.CharField(max_length=100, verbose_name='Nomor Surat')),
                ('orang_tua', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama Orang Tua')),
                ('alasan_panggilan', models.TextField(verbose_name='Alasan Panggilan')),
                ('tempat_panggilan', models.CharField(max_length=100, verbose_name='Tempat Panggilan')),
                ('tanggal_panggilan', models.DateField(verbose_name='Tanggal Panggilan')),
                ('waktu_panggilan', models.TimeField(verbose_name='Waktu Panggilan')),
                ('tempat_ditetapkan', models.CharField(max_length=100, verbose_name='Tempat Ditetapkan')),
                ('tanggal_ditetapkan', models.DateField(verbose_name='Tanggal Ditetapkan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kop_surat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asn_app.kopsurat', verbose_name='Kop Surat')),
                ('penandatangan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surat_panggilan_penandatangan', to='asn_app.asn', verbose_name='Penandatangan')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surat_panggilan', to='asn_app.siswa', verbose_name='Siswa')),
            ],
            options={
                'verbose_name_plural': 'Surat Panggilan Siswa',
                'ordering': ['-tanggal_ditetapkan'],
            },
        ),
    ]
