# Generated by Django 4.2.27 on 2026-03-31 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0046_suratpanggilansiswa'),
    ]

    operations = [
        migrations.AddField(
            model_name='suratpanggilansiswa',
            name='keterangan_panggilan',
            field=models.CharField(choices=[('1', 'ke-1 (Satu)'), ('2', 'ke-2 (Dua)'), ('3', 'ke-3 (Tiga)'), ('4', 'ke-4 (Empat)')], default='1', max_length=1, verbose_name='Panggilan Ke-'),
        ),
    ]
