# Generated by Django 4.2.27 on 2026-03-31 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0047_suratpanggilansiswa_keterangan_panggilan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suratpanggilansiswa',
            name='penandatangan',
        ),
        migrations.AddField(
            model_name='suratpanggilansiswa',
            name='guru_bk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guru_bk_panggilan', to='asn_app.asn', verbose_name='Guru BK'),
        ),
        migrations.AddField(
            model_name='suratpanggilansiswa',
            name='wakasek_kesiswaan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wakasek_kesiswaan_panggilan', to='asn_app.asn', verbose_name='Wakasek Kesiswaan'),
        ),
        migrations.AddField(
            model_name='suratpanggilansiswa',
            name='wali_kelas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wali_kelas_panggilan', to='asn_app.asn', verbose_name='Wali Kelas'),
        ),
    ]
