# Generated by Django 4.2.27 on 2026-05-04 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0048_remove_suratpanggilansiswa_penandatangan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiswaKeluar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_keluar', models.DateField(verbose_name='Tanggal Keluar')),
                ('alasan_keluar', models.TextField(verbose_name='Alasan Keluar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keluar', to='asn_app.siswa', verbose_name='Siswa')),
            ],
            options={
                'verbose_name': 'Siswa Keluar',
                'verbose_name_plural': 'Siswa Keluar',
                'ordering': ['-tanggal_keluar'],
            },
        ),
    ]
