# Generated by Django 4.2.27 on 2026-06-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0049_siswakeluar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asn',
            name='golongan',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='asn',
            name='pangkat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
