# Generated by Django 4.2.30 on 2026-07-10 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0050_alter_asn_golongan_alter_asn_pangkat'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuratRekomendasiStudiLanjut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_surat', models.CharField(max_length=100, verbose_name='Nomor Surat')),
                ('instansi', models.CharField(max_length=200, verbose_name='Nama Instansi/Sekolah/Organisasi')),
                ('nama_universitas', models.CharField(max_length=200, verbose_name='Nama Universitas/Kampus')),
                ('program_studi', models.CharField(max_length=200, verbose_name='Nama Program Studi')),
                ('pertimbangan', models.TextField(blank=True, default='1. Pegawai yang bersangkutan memiliki dedikasi dan kinerja yang baik selama bekerja di instansi kami.\n2. Bidang ilmu yang akan dipelajari relevan dengan kebutuhan pengembangan kompetensi serta peningkatan efektivitas pelayanan di unit kerja kami.\n3. Pegawai memiliki potensi akademik yang baik serta kemampuan untuk mengaplikasikan ilmu yang didapat bagi kemajuan instansi.', verbose_name='Pertimbangan Rekomendasi')),
                ('tempat_ditetapkan', models.CharField(max_length=100, verbose_name='Tempat Ditetapkan')),
                ('tanggal_ditetapkan', models.DateField(verbose_name='Tanggal Ditetapkan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kop_surat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asn_app.kopsurat', verbose_name='Kop Surat')),
                ('pegawai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rekomendasi_pegawai', to='asn_app.asn', verbose_name='Pegawai')),
                ('penandatangan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rekomendasi_penandatangan', to='asn_app.asn', verbose_name='Pimpinan (Atasan)')),
            ],
            options={
                'verbose_name_plural': 'Surat Rekomendasi Studi Lanjut',
                'ordering': ['-tanggal_ditetapkan'],
            },
        ),
    ]
