# Generated by Django 4.2.30 on 2026-07-10 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0051_suratrekomendasistudilanjut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suratrekomendasistudilanjut',
            name='pertimbangan',
            field=models.TextField(blank=True, default='Pegawai yang bersangkutan memiliki dedikasi dan kinerja yang baik selama bekerja di instansi kami.\nBidang ilmu yang akan dipelajari relevan dengan kebutuhan pengembangan kompetensi serta peningkatan efektivitas pelayanan di unit kerja kami.\nPegawai memiliki potensi akademik yang baik serta kemampuan untuk mengaplikasikan ilmu yang didapat bagi kemajuan instansi.', verbose_name='Pertimbangan Rekomendasi'),
        ),
        migrations.CreateModel(
            name='SuratKP4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_kepegawaian', models.CharField(blank=True, max_length=100, null=True, verbose_name='Status Kepegawaian')),
                ('masa_kerja_golongan', models.CharField(blank=True, max_length=100, null=True, verbose_name='Masa Kerja Golongan')),
                ('digaji_menurut', models.CharField(blank=True, max_length=255, null=True, verbose_name='Digaji Menurut')),
                ('tempat_ditetapkan', models.CharField(max_length=100, verbose_name='Tempat Ditetapkan')),
                ('tanggal_ditetapkan', models.DateField(verbose_name='Tanggal Ditetapkan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kop_surat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asn_app.kopsurat', verbose_name='Kop Surat')),
                ('pegawai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kp4_pegawai', to='asn_app.asn', verbose_name='Pegawai (Yang Menerangkan)')),
                ('penandatangan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kp4_penandatangan', to='asn_app.asn', verbose_name='Kepala (Mengetahui)')),
            ],
            options={
                'verbose_name_plural': 'Surat KP4 (Tunjangan Keluarga)',
                'ordering': ['-tanggal_ditetapkan'],
            },
        ),
        migrations.CreateModel(
            name='AnggotaKeluargaKP4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, verbose_name='Nama Istri/Suami/Tanggungan')),
                ('tanggal_kelahiran', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tanggal Kelahiran')),
                ('tanggal_perkawinan', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tanggal Perkawinan')),
                ('pekerjaan', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pekerjaan')),
                ('keterangan', models.CharField(blank=True, max_length=100, null=True, verbose_name='Keterangan')),
                ('mendapat_tunjangan', models.BooleanField(default=True, verbose_name='Mendapat Tunjangan')),
                ('surat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anggota_keluarga', to='asn_app.suratkp4', verbose_name='Surat KP4')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
