# Generated by Django 4.2.30 on 2026-07-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0052_alter_suratrekomendasistudilanjut_pertimbangan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suratkp4',
            name='digaji_menurut',
            field=models.CharField(blank=True, default='PP Nomor 05 Tahun 2024 (CPNS dan PNS), Perpres Nomor 11 Tahun 2024 (PPPK)', max_length=255, null=True, verbose_name='Digaji Menurut'),
        ),
    ]
