# Generated by Django 4.2.30 on 2026-07-10 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0053_alter_suratkp4_digaji_menurut'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuratUndanganSiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_surat', models.CharField(max_length=100, verbose_name='Nomor Surat')),
                ('orang_tua', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama Orang Tua')),
                ('perihal', models.CharField(default='Undangan Orang Tua Siswa', max_length=200, verbose_name='Perihal')),
                ('isi_undangan', models.TextField(verbose_name='Isi/Maksud Undangan')),
                ('tempat', models.CharField(max_length=100, verbose_name='Tempat')),
                ('tanggal', models.DateField(verbose_name='Tanggal Undangan')),
                ('waktu', models.TimeField(verbose_name='Waktu Undangan')),
                ('tempat_ditetapkan', models.CharField(max_length=100, verbose_name='Tempat Ditetapkan')),
                ('tanggal_ditetapkan', models.DateField(verbose_name='Tanggal Ditetapkan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kepala_sekolah', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kepala_sekolah_undangan', to='asn_app.asn', verbose_name='Kepala Sekolah')),
                ('kop_surat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asn_app.kopsurat', verbose_name='Kop Surat')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surat_undangan', to='asn_app.siswa', verbose_name='Siswa')),
            ],
            options={
                'verbose_name_plural': 'Surat Undangan Siswa',
                'ordering': ['-tanggal_ditetapkan'],
            },
        ),
    ]
