# Generated by Django 4.2.30 on 2026-07-10 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0054_suratundangansiswa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suratundangansiswa',
            name='siswa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surat_undangan', to='asn_app.siswa', verbose_name='Siswa'),
        ),
    ]
