# Generated by Django 4.2.30 on 2026-07-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0055_alter_suratundangansiswa_siswa'),
    ]

    operations = [
        migrations.AddField(
            model_name='notadinas',
            name='siswa',
            field=models.ManyToManyField(blank=True, related_name='nota_dinas_siswa', to='asn_app.siswa'),
        ),
    ]
