# Generated by Django 4.2.30 on 2026-07-10 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0056_notadinas_siswa'),
    ]

    operations = [
        migrations.CreateModel(
            name='PesertaNotaDinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidang_lomba', models.CharField(blank=True, max_length=255, verbose_name='Bidang Lomba')),
                ('peran', models.CharField(choices=[('Peserta', 'Peserta'), ('Pendamping', 'Pendamping'), ('Toolman', 'Toolman'), ('Kepsek', 'Kepsek / Penanggungjawab'), ('Bendahara', 'Bendahara')], default='Peserta', max_length=50, verbose_name='Peran')),
                ('nota_dinas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peserta_nota_dinas', to='asn_app.notadinas')),
                ('pegawai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asn_app.asn', verbose_name='Pegawai')),
                ('siswa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asn_app.siswa', verbose_name='Siswa')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
