# Generated by Django 4.2.30 on 2026-07-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0057_pesertanotadinas'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswa',
            name='status',
            field=models.CharField(choices=[('Aktif', 'Aktif'), ('Lulus', 'Lulus'), ('Keluar', 'Keluar'), ('DO', 'DO')], default='Aktif', max_length=20),
        ),
    ]
