# Generated by Django 4.2.30 on 2026-07-11 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0058_siswa_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuratDispensasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_surat', models.CharField(max_length=100, verbose_name='Nomor Surat')),
                ('nama_kegiatan', models.CharField(max_length=200, verbose_name='Nama Kegiatan')),
                ('hari_tanggal', models.CharField(help_text='cth: Senin s.d Selasa, 12 s.d 13 Pebruari 2024', max_length=200, verbose_name='Hari/Tanggal')),
                ('waktu', models.CharField(help_text='cth: 10.00 Wita - Selesai', max_length=100, verbose_name='Waktu')),
                ('tempat', models.CharField(max_length=200, verbose_name='Tempat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kop_surat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asn_app.kopsurat', verbose_name='Kop Surat')),
                ('penandatangan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surat_dispensasi_penandatangan', to='asn_app.asn', verbose_name='Kepala Sekolah (Penandatangan)')),
            ],
            options={
                'verbose_name_plural': 'Surat Dispensasi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PesertaDispensasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ket', models.CharField(choices=[('Siswa', 'Siswa'), ('Pembina', 'Pembina')], default='Siswa', max_length=20, verbose_name='Keterangan')),
                ('guru', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asn_app.asn', verbose_name='Guru/Pembina')),
                ('siswa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asn_app.siswa', verbose_name='Siswa')),
                ('surat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peserta_dispensasi', to='asn_app.suratdispensasi')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
