# Generated by Django 4.2.30 on 2026-07-11 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0059_suratdispensasi_pesertadispensasi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suratdispensasi',
            name='hari_tanggal',
        ),
        migrations.AddField(
            model_name='suratdispensasi',
            name='tanggal_akhir',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Akhir'),
        ),
        migrations.AddField(
            model_name='suratdispensasi',
            name='tanggal_awal',
            field=models.DateField(default=datetime.date(2024, 2, 12), verbose_name='Tanggal Awal'),
            preserve_default=False,
        ),
    ]
