# Generated by Django 4.2.30 on 2026-07-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0060_remove_suratdispensasi_hari_tanggal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suratdispensasi',
            name='tanggal_ditetapkan',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Ditetapkan'),
        ),
        migrations.AddField(
            model_name='suratdispensasi',
            name='tempat_ditetapkan',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tempat Ditetapkan'),
        ),
    ]
