# Generated by Django 4.2.30 on 2026-07-14 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0061_suratdispensasi_tanggal_ditetapkan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuratUsulan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kepada', models.CharField(max_length=255)),
                ('dari', models.CharField(max_length=255)),
                ('tanggal', models.DateField()),
                ('nomor', models.CharField(max_length=255)),
                ('sifat', models.CharField(max_length=255)),
                ('lampiran', models.CharField(max_length=255)),
                ('hal', models.CharField(max_length=255)),
                ('dasar_surat', models.TextField(verbose_name='Dasar Surat')),
                ('isi_surat', models.TextField()),
                ('penutup_surat', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kop_surat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asn_app.kopsurat')),
                ('penanda_tangan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penanda_tangan_surat_usulan', to='asn_app.asn')),
            ],
        ),
        migrations.CreateModel(
            name='PesertaSuratUsulan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_tempat', models.CharField(max_length=255, verbose_name='Tanggal / Tempat')),
                ('pegawai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asn_app.asn', verbose_name='Pegawai')),
                ('surat_usulan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peserta_surat_usulan', to='asn_app.suratusulan')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
