# Generated by Django 4.2.30 on 2026-07-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0062_add_suratusulan_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesertasuratusulan',
            name='tanggal_tempat',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tanggal / Tempat'),
        ),
    ]
