# Generated by Django 4.2.30 on 2026-07-14 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0063_make_tanggal_tempat_optional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suratusulan',
            name='isi_surat',
        ),
    ]
