# Generated by Django 4.2.30 on 2026-07-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0064_remove_isi_surat_from_suratusulan'),
    ]

    operations = [
        migrations.AddField(
            model_name='suratusulan',
            name='isi_surat',
            field=models.TextField(default=''),
        ),
    ]
