# Generated by Django 4.2.30 on 2026-07-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0065_restore_isi_surat_to_suratusulan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesertasuratusulan',
            name='tanggal_tempat',
        ),
        migrations.AddField(
            model_name='pesertasuratusulan',
            name='tanggal_kegiatan',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Kegiatan'),
        ),
        migrations.AddField(
            model_name='pesertasuratusulan',
            name='tempat_kegiatan',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tempat Kegiatan'),
        ),
    ]
