# Generated by Django 4.2.30 on 2026-07-14 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0066_split_tanggal_tempat_to_tanggal_tempat_kegiatan'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesertasuratusulan',
            name='siswa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asn_app.siswa', verbose_name='Siswa'),
        ),
    ]
