# Generated by Django 4.2.30 on 2026-07-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0067_add_siswa_to_peserta_surat_usulan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suratusulan',
            name='isi_surat',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
