# Generated by Django 4.2.30 on 2026-07-15 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0068_make_isi_surat_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='StSatyalancana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dasar_surat', models.TextField(verbose_name='Dasar Surat')),
                ('kepada_nama', models.CharField(max_length=255, verbose_name='Nama')),
                ('kepada_nip', models.CharField(max_length=255, verbose_name='NIP')),
                ('kepada_pangkat_gol', models.CharField(max_length=255, verbose_name='Pangkat / Golongan')),
                ('kepada_jabatan', models.CharField(max_length=255, verbose_name='Jabatan')),
                ('kepada_unit_kerja', models.CharField(max_length=255, verbose_name='Unit Kerja')),
                ('untuk_tugas', models.TextField(verbose_name='Untuk Ditujukan')),
                ('nomor', models.CharField(max_length=255)),
                ('tanggal', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kop_surat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asn_app.kopsurat')),
                ('penanda_tangan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penanda_tangan_st_satyalancana', to='asn_app.asn')),
            ],
        ),
    ]
