# Generated by Django 4.2.30 on 2026-07-15 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0069_add_st_satyalancana_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='stsatyalancana',
            name='kepada_pegawai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asn_app.asn', verbose_name='Kepada Pegawai'),
        ),
        migrations.AlterField(
            model_name='stsatyalancana',
            name='kepada_jabatan',
            field=models.CharField(blank=True, max_length=255, verbose_name='Jabatan'),
        ),
        migrations.AlterField(
            model_name='stsatyalancana',
            name='kepada_nama',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nama'),
        ),
        migrations.AlterField(
            model_name='stsatyalancana',
            name='kepada_nip',
            field=models.CharField(blank=True, max_length=255, verbose_name='NIP'),
        ),
        migrations.AlterField(
            model_name='stsatyalancana',
            name='kepada_pangkat_gol',
            field=models.CharField(blank=True, max_length=255, verbose_name='Pangkat / Golongan'),
        ),
        migrations.AlterField(
            model_name='stsatyalancana',
            name='kepada_unit_kerja',
            field=models.CharField(blank=True, max_length=255, verbose_name='Unit Kerja'),
        ),
    ]
