# Generated by Django 4.2.30 on 2026-07-15 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0070_add_kepada_pegawai_to_st_satyalancana'),
    ]

    operations = [
        migrations.CreateModel(
            name='DRHSatyalancana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip_lama', models.CharField(blank=True, max_length=255, verbose_name='NIP Lama')),
                ('pendidikan_terakhir', models.CharField(blank=True, max_length=255, verbose_name='Pendidikan Terakhir')),
                ('pangkat_golongan', models.CharField(blank=True, max_length=255, verbose_name='Pangkat, Gol. Ruang Terakhir (TMT)')),
                ('no_sk_cpns', models.CharField(blank=True, max_length=255, verbose_name='No. SK CPNS (TMT)')),
                ('jabatan_terakhir', models.CharField(blank=True, max_length=255, verbose_name='Jabatan Terakhir (TMT)')),
                ('tanda_kehormatan', models.TextField(blank=True, verbose_name='Tanda Kehormatan yang sudah dimiliki')),
                ('hukuman_disiplin', models.TextField(blank=True, verbose_name='Hukuman Disiplin')),
                ('cltn', models.TextField(blank=True, verbose_name='CLTN')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drh_satyalancana', to='asn_app.asn')),
            ],
        ),
    ]
