# Generated by Django 4.2.30 on 2026-07-16 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0071_add_drh_satyalancana_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='drhsatyalancana',
            name='atasan_langsung',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drh_atasan_langsung', to='asn_app.asn', verbose_name='Atasan Langsung'),
        ),
    ]
