# Generated by Django 4.2.30 on 2026-07-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0072_add_atasan_langsung_to_drh'),
    ]

    operations = [
        migrations.AddField(
            model_name='drhsatyalancana',
            name='no_kepres',
            field=models.CharField(blank=True, max_length=255, verbose_name='No. Keppres'),
        ),
        migrations.AddField(
            model_name='drhsatyalancana',
            name='tgl_kepres',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Keppres'),
        ),
        migrations.AddField(
            model_name='drhsatyalancana',
            name='tmt_cpns',
            field=models.DateField(blank=True, null=True, verbose_name='TMT CPNS'),
        ),
        migrations.AddField(
            model_name='drhsatyalancana',
            name='tmt_jabatan',
            field=models.DateField(blank=True, null=True, verbose_name='TMT Jabatan'),
        ),
        migrations.AddField(
            model_name='drhsatyalancana',
            name='tmt_pangkat',
            field=models.DateField(blank=True, null=True, verbose_name='TMT Pangkat'),
        ),
    ]
