# Generated by Django 4.2.30 on 2026-07-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0073_add_drh_kepres_and_tmt_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drhsatyalancana',
            name='pangkat_golongan',
            field=models.CharField(blank=True, choices=[('Pembina Utama,IV/e', 'Pembina Utama, IV/e'), ('Pembina Utama Mady,IV/d', 'Pembina Utama Mady, IV/d'), ('Pembina Utama Muda,IV/c', 'Pembina Utama Muda, IV/c'), ('Pembina Tingkat I,IV/b', 'Pembina Tingkat I, IV/b'), ('Pembina,IV/a', 'Pembina, IV/a'), ('Penata Tingkat I,III/d', 'Penata Tingkat I, III/d'), ('Penata,III/c', 'Penata, III/c'), ('Penata Muda Tingkat I,III/b', 'Penata Muda Tingkat I, III/b'), ('Penata Muda,III/a', 'Penata Muda, III/a'), ('Pengatur Tingkat I,II/d', 'Pengatur Tingkat I, II/d'), ('Pengatur,II/c', 'Pengatur, II/c'), ('Pengatur Muda Tingkat I,II/b', 'Pengatur Muda Tingkat I, II/b'), ('Pengatur Muda,II/a', 'Pengatur Muda, II/a'), ('Juru Tingkat I,I/d', 'Juru Tingkat I, I/d'), ('Juru,I/c', 'Juru, I/c'), ('Juru Muda Tingkat I,I/b', 'Juru Muda Tingkat I, I/b'), ('Juru Muda,I/a', 'Juru Muda, I/a')], max_length=255, verbose_name='Pangkat, Gol. Ruang Terakhir (TMT)'),
        ),
    ]
