# Generated by Django 4.2.30 on 2026-07-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0074_add_pangkat_gol_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='asn',
            name='jabatan_terakhir',
            field=models.CharField(blank=True, max_length=255, verbose_name='Jabatan Terakhir'),
        ),
        migrations.AddField(
            model_name='asn',
            name='pendidikan_terakhir',
            field=models.CharField(blank=True, max_length=255, verbose_name='Pendidikan Terakhir'),
        ),
        migrations.AddField(
            model_name='asn',
            name='tmt_cpns',
            field=models.DateField(blank=True, null=True, verbose_name='TMT CPNS'),
        ),
        migrations.AddField(
            model_name='asn',
            name='tmt_jabatan',
            field=models.DateField(blank=True, null=True, verbose_name='TMT Jabatan'),
        ),
        migrations.AddField(
            model_name='asn',
            name='tmt_pangkat',
            field=models.DateField(blank=True, null=True, verbose_name='TMT Pangkat'),
        ),
    ]
