# Generated by Django 4.2.30 on 2026-07-16 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0075_add_auto_fill_fields_to_asn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asn',
            name='jabatan_terakhir',
        ),
    ]
