# Generated by Django 4.2.30 on 2026-07-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0076_remove_jabatan_terakhir_from_asn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drhsatyalancana',
            name='pangkat_golongan',
        ),
        migrations.AddField(
            model_name='drhsatyalancana',
            name='golongan',
            field=models.CharField(blank=True, max_length=255, verbose_name='Golongan'),
        ),
        migrations.AddField(
            model_name='drhsatyalancana',
            name='pangkat',
            field=models.CharField(blank=True, max_length=255, verbose_name='Pangkat'),
        ),
    ]
