# Generated by Django 4.2.30 on 2026-07-16 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0078_rename_suratundangansiswa_to_suratundangan_and_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suratundangan',
            options={'ordering': ['-tanggal_ditetapkan'], 'verbose_name_plural': 'Surat Undangan'},
        ),
    ]
