# Generated by Django 4.2.30 on 2026-07-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0079_alter_suratundangan_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='suratundangan',
            name='pembuka_surat',
            field=models.TextField(blank=True, null=True, verbose_name='Pembuka Surat'),
        ),
        migrations.AddField(
            model_name='suratundangan',
            name='penutup_surat',
            field=models.TextField(blank=True, null=True, verbose_name='Penutup Surat'),
        ),
        migrations.AlterField(
            model_name='suratundangan',
            name='isi_undangan',
            field=models.TextField(blank=True, null=True, verbose_name='Isi/Maksud Undangan'),
        ),
    ]
