# Generated by Django 4.2.27 on 2026-07-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0082_remove_dasar_surat_from_spt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dasarsurat',
            name='isi',
            field=models.TextField(blank=True, verbose_name='Dasar Surat'),
        ),
        migrations.AlterField(
            model_name='dasarsurat',
            name='urutan',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Urutan'),
        ),
    ]
