# Generated by Django 4.2.30 on 2026-07-18 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0083_alter_dasarsurat_isi_alter_dasarsurat_urutan'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuratPengantar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_surat', models.CharField(max_length=100, verbose_name='Nomor Surat')),
                ('tempat_ditetapkan', models.CharField(max_length=100, verbose_name='Tempat Ditetapkan')),
                ('tanggal_surat', models.DateField(verbose_name='Tanggal Surat')),
                ('tujuan_surat', models.CharField(max_length=255, verbose_name='Tujuan Surat')),
                ('isi_surat', models.TextField(blank=True, null=True, verbose_name='Isi Surat')),
                ('nomor_telepon', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nomor Telepon')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kop_surat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asn_app.kopsurat', verbose_name='Kop Surat')),
                ('penandatangan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surat_pengantar_penandatangan', to='asn_app.asn', verbose_name='Penandatangan')),
            ],
            options={
                'verbose_name_plural': 'Surat Pengantar',
                'ordering': ['-tanggal_surat'],
            },
        ),
    ]
