# Generated by Django 4.2.30 on 2026-07-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asn_app', '0084_surat_pengantar'),
    ]

    operations = [
        migrations.AddField(
            model_name='suratpengantar',
            name='banyaknya',
            field=models.CharField(default='1 (satu) berkas', max_length=100, verbose_name='Banyaknya'),
        ),
        migrations.AddField(
            model_name='suratpengantar',
            name='keterangan',
            field=models.CharField(default='Demikian disampaikan untuk dapat di tindaklanjuti', max_length=255, verbose_name='Keterangan'),
        ),
        migrations.AlterField(
            model_name='suratpengantar',
            name='isi_surat',
            field=models.TextField(blank=True, null=True, verbose_name='Naskah Dinas/Barang yang Dikirimkan'),
        ),
    ]
